kind: Service
apiVersion: v1
metadata:
  name: ethereum-blockchain-service-service
spec:
  selector:
    app: ethereum-blockchain-service
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000